name: bild
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1
environment:
  sdk: ">=3.5.4 <4.0.0"  # Aquí es donde debe ir el sdk de Flutter
  
dependencies:
  firebase_core: ^2.19.0  # Dependencia de firebase_core
  firebase_auth: ^4.4.0  # Si necesitas usar autenticación
  cloud_firestore: ^4.8.0  # Si deseas usar Firestore
  cupertino_icons: ^1.0.8  # Dependencia de cupertino_icons
  uses-material-design: true

flutter:
  # La sección de flutter solo contiene configuraciones específicas de Flutter
  sdk: flutter  # Esta línea debe estar aquí

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
