// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXf9dHUN7HtNVFcoULqvMUpOLObUqCUig',
    appId: '1:270954655029:web:06ea6ef6c6b195a8a2f07c',
    messagingSenderId: '270954655029',
    projectId: 'bild-f7e2f',
    authDomain: 'bild-f7e2f.firebaseapp.com',
    storageBucket: 'bild-f7e2f.firebasestorage.app',
    measurementId: 'G-72ZT6KPX6N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzRBdW0mHh7o8qeU4XtFQeXjvnpyVLSws',
    appId: '1:270954655029:android:dba499e1576e89a3a2f07c',
    messagingSenderId: '270954655029',
    projectId: 'bild-f7e2f',
    storageBucket: 'bild-f7e2f.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXf9dHUN7HtNVFcoULqvMUpOLObUqCUig',
    appId: '1:270954655029:web:f05f282d2f13086ba2f07c',
    messagingSenderId: '270954655029',
    projectId: 'bild-f7e2f',
    authDomain: 'bild-f7e2f.firebaseapp.com',
    storageBucket: 'bild-f7e2f.firebasestorage.app',
    measurementId: 'G-PN7DD0GBP9',
  );
}

